openapi: 3.0.0
info:
  title: User API
  version: 1.0.0

paths:
  /users:
    get:
      summary: Returns a list of users
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /users/{id}:
    get:
      summary: Returns a user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string

  /users:
    post:
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string

  /business:
    post:
      summary: Add a new business
      description: Adds a new business to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                businessName:
                  type: string
                  example: "My Business"
                businessDescription:
                  type: string
                  example: "This is a description of my business."
                businessEmail:
                  type: string
                  example: "business@example.com"
                businessPhone:
                  type: string
                  example: "+1234567890"
      responses:
        '201':
          description: Successfully added
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  businessName:
                    type: string
                    example: "My Business"
                  businessDescription:
                    type: string
                    example: "This is a description of my business."
                  businessEmail:
                    type: string
                    example: "business@example.com"
                  businessPhone:
                    type: string
                    example: "+1234567890"

  /business/{id}:
    put:
      summary: Update an existing business
      description: Updates an existing business in the system
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                businessName:
                  type: string
                  example: "Updated Business"
                businessDescription:
                  type: string
                  example: "This is an updated description of my business."
                businessEmail:
                  type: string
                  example: "updated_business@example.com"
                businessPhone:
                  type: string
                  example: "+0987654321"
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  businessName:
                    type: string
                    example: "Updated Business"
                  businessDescription:
                    type: string
                    example: "This is an updated description of my business."
                  businessEmail:
                    type: string
                    example: "updated_business@example.com"
                  businessPhone:
                    type: string
                    example: "+0987654321"
